# Generated by Django 5.1.6 on 2025-03-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_category_slug_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='discount_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
